name:                straw-poll-server
version:             0.1.0.0
github:              "githubuser/straw-poll-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/straw-poll-server#readme>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- BangPatterns
- DeriveGeneric
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- TupleSections
- TypeApplications
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- http-types
- postgresql-simple
- resource-pool
- text
- time
- wai
- warp

library:
  source-dirs: src

executables:
  straw-poll-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - straw-poll-server

tests:
  straw-poll-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - straw-poll-server
    - hspec
    - hspec-wai
    - hspec-wai-json
