FROM haskell:8.8.4

RUN apt-get update \
 && apt-get install --yes libpq-dev \
 && mkdir -p /opt/build
WORKDIR /opt/build

COPY stack.yaml stack.yaml.lock package.yaml ./
RUN stack build --system-ghc --dependencies-only
