version: "3.8"

volumes:
  database-data:

services:
  database:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=straw_poll
      - POSTGRES_PASSWORD=${STRAW_POLL_PG_MIGRATE_PASSWORD:-postgres}
      - POSTGRES_USER=${STRAW_POLL_PG_MIGRATE_USER:-postgres}
    ports:
      - "${STRAW_POLL_PG_PORT:-7777}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  migrate-database:
    build: .
    environment:
      - STRAW_POLL_PG_HOST=database
      - STRAW_POLL_PG_PORT=5432
      - STRAW_POLL_PG_MIGRATE_USER=${STRAW_POLL_PG_MIGRATE_USER:-postgres}
      - STRAW_POLL_PG_MIGRATE_PASSWORD=${STRAW_POLL_PG_MIGRATE_PASSWORD:-postgres}
    depends_on:
      - database
